---
title: "PCA"
output: html_document
---

PCA Analysis based on the transformed df "full_best_df.csv"

```{r, echo = TRUE, fig.width=8, fig.height=8}
#------------------------------------------LOADING-------------------------------------------------
require(FactoMineR)
require(dplyr)
require(ggplot2)
require(ggcorrplot)
require(bestNormalize)
require(reshape2)
require(factoextra)

full_best_df <- read.csv("C:/Users/A541U/Desktop/Semester 2/Descriptive R Project/2018_World_Happiness_Multivariate_Analysis/DATA/full_best_df.csv")

temp_df <- full_best_df %>% 
  select(-X,-Country,-Region,-Happiness_Score,
         -Total_Population,-Mental_and_Substance_Disorder_Index,-Compulsory_Education_in_Years,-Agricultural_Land_Percentage,-Generosity,-Forest_Area_Land_Percentage,-Suicide_Index,-Legal_Rights_Index)
```

PCA Function and biplot of 2 first Principal components:
```{r, echo = TRUE, fig.width=8, fig.height=8}
res.pca <- PCA(temp_df,graph=T)
```

Eigenvalues and first 10 individuals/variables correlation to the 3 first PCs:
```{r, echo = TRUE, fig.width=8, fig.height=8}
summary(res.pca)
```

Correlation of each variable to the 3 first PCs:
```{r, echo = TRUE, fig.width=8, fig.height=8}
dimdesc(res.pca) #Easy way to see the contribution of each component's variables
res.pca$var$coord #Easier to compare the contribution of each variables to the components
```


Linear Regression on Happiness Score with the PCs: (just started)
```{r, echo = TRUE, fig.width=8, fig.height=8}

pccc <- pca1$ind$coord[,1:3]
lm <- lm(full_best_df$Happiness_Score ~ pccc)
plot(lm)
```
